version: "3.7"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: growdash-backend
    hostname: backend
    image: growdash-backend
    ports:
      - "${GROWDASH_BACKEND_PORT:-8000}:${GROWDASH_BACKEND_PORT:-8000}"
    env_file:
      - ./backend/.env
    command: uvicorn src:app --host 0.0.0.0 --reload
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: growdash-frontend
  #   hostname: frontend
  #   image: growdash-frontend
  #   ports:
  #     - "${GROWDASH_FRONTEND_PORT:-3000}:${GROWDASH_FRONTEND_PORT:-3000}"
  #   env_file:
  #     - ./frontend/.env
